/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gingytech_gtm_app_hybrid_SerialPort */

#ifndef _Included_com_gingytech_gtm_app_hybrid_SerialPort
#define _Included_com_gingytech_gtm_app_hybrid_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gingytech_gtm_app_hybrid_SerialPort
 * Method:    native_open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_gingytech_gtm_app_hybrid_SerialPort_native_1open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_gingytech_gtm_app_hybrid_SerialPort
 * Method:    native_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gingytech_gtm_app_hybrid_SerialPort_native_1close
  (JNIEnv *, jobject);

/*
 * Class:     com_gingytech_gtm_app_hybrid_SerialPort
 * Method:    native_read_array
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_gingytech_gtm_app_hybrid_SerialPort_native_1read_1array
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_gingytech_gtm_app_hybrid_SerialPort
 * Method:    native_write_array
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_gingytech_gtm_app_hybrid_SerialPort_native_1write_1array
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_gingytech_gtm_app_hybrid_SerialPort
 * Method:    native_clean_read_array
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gingytech_gtm_app_hybrid_SerialPort_native_1clean_1read_1array
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
